# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 04:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_user_profile_pic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkin',
            options={'ordering': ['-check_in_time']},
        ),
    ]
