# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_disc_friend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disc',
            name='weight',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
