# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_checkinimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updates', models.CharField(max_length=999)),
                ('coming_soon', models.CharField(max_length=999)),
            ],
        ),
    ]
