# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-18 05:32
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20171129_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
