# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='coming_soon',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='updates',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
    ]
